version: '3.3'
services:
  apache:
    build:
      context: ./Apache
    image: nurseryqueueapi/apache
    container_name: nurseryqueueapi_apache
    environment:
      - MODCLUSTER_PORT=9999
      - MODCLUSTER_ADVERTISE=Off
    ports:
     - "23364:23364"
     - "9999:9999"
  nurseryqueueapi:
    build:
      context: ./NurseryQueueApi
    image: nurseryqueueapi/nurseryqueueapi
    container_name: nurseryqueueapi
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug

networks:
  default:
    external:
      name: nq